### ISSUE TITLE
关于代码块的样式

### ISSUE THREAD

**Issue by qi-jasper** [jinghu-moon/typora-see-yue-theme#1]
代码块模仿 mac 窗口的部分，我希望把窗口的那个高度改一下，我觉得太高了，真实的 mac 窗口框是很矮（窄）的。我不太会 CSS，我有尝试修改，但是改完以后代码语言和你模仿的窗口按钮就会出来

**Comment by jinghu-moon** [comment]
修改后，效果如下：

![](https://s3.bmp.ovh/imgs/2022/06/25/75bac73dce3b82da.png)

修改如下：

```css
/* code-language.css 文件 */
pre.md-fences:before {
    content: " ";
    background: #fc625d;
    /* 阴影模拟小圆点 */
    /* 参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-shadow */
    box-shadow: 25px 0 #fdbc40, 50px 0 #35cd4b;
    border-radius: 50%;
    position: absolute;
    /* 调整高度 */
    top: -20px;
    left: 10px;
    height: 11px;
    width: 11px;
}

#write pre.md-fences {
    /* 边框宽度 */
    border-top: 30px solid rgb(167, 187, 195, 0.6);
}

/* 代码语言显示 */
pre::after {
    font-family: "Lora-Regular";
    position: absolute;
    /* 调整高度 */
    top: -29px;
    font-weight: bold;
    /* 调整右边距 */
    right: 1%;
    z-index: 99;
    /* 调整大小 */
    font-size: .85rem;
    /* 字间距 */
    letter-spacing: 1px;
}
```

主要是调整 `top`、`font-size`、`border-top` 属性。
下一个版本，我将会修改代码块仿 Mac 窗口样式。目前版本的代码块边框的确有点高。

感谢反馈 😘
