### ISSUE TITLE
选中文本极易把前面所有内容全部选中

### ISSUE THREAD

**Issue by dselegent** [jinghu-moon/typora-see-yue-theme#11]

**Comment by dselegent** [comment]
https://vkceyugu.cdn.bspapp.com/VKCEYUGU-ba5c88cc-6c27-4065-a291-97fd288eea80/887ea050-9633-44a9-a81c-184df64d06d1.mp4
我录制了一下放这个地址里了

**Comment by jinghu-moon** [comment]
以前我在测试主题的时候。遇到过这现象。但是我没有特别关注这个问题。因为后面这个问题突然就不见了（当时我猜测这个问题可能跟用户的使用习惯有关），且我的朋友在使用过程中没有遇到这种情况。
现在看来可能跟我的主题有一定关系。目前还没有定位到 bug 代码，你有找到相应代码吗？

**Comment by dselegent** [comment]
> 

这个我还真找不到，不会又是因为内容太多导致的吧，这个文件当时是1000行左右

**Comment by jinghu-moon** [comment]
注释掉以下代码，即可解决问题。

```css
/* see-yue.css 文件开头 */
#write::before,
write::after {
  content              : "";
  display              : block;
  width                : 100%;
  backdrop-filter      : blur(var(--interface-default-bg-img-blur));
  position             : absolute;
  top                  : 0;
  left                 : 0;
  right                : 0;
  bottom               : 0;
  z-index              : -99;
  min-height           : 100%;
  border-radius        : 5px;
  background-blend-mode: overlay;
}
```
