### ISSUE TITLE
列表中使用代码块，导致代码块仿 Mac 窗口样式失效

### ISSUE THREAD

**Issue by HyHydromechanics** [jinghu-moon/typora-see-yue-theme#12]
在使用的时候只有第一个代码块会有类似mac窗口的装饰
<img width="837" alt="截屏2022-08-07 17 28 31" src="https://user-images.githubusercontent.com/87158955/183284449-9cf551cd-2ae8-46d5-9410-c71bb2d8e0f8.png">
<img width="837" alt="截屏2022-08-07 17 28 40" src="https://user-images.githubusercontent.com/87158955/183284454-2db35d1e-1eaf-49d1-9d8e-77cf878c4d23.png">

**Comment by jinghu-moon** [comment]
**解决方法**

`code-language.css` 文件修改如下：
```css
pre.md-fences:before {
  content      : " ";
  /* height、width、background 加 !important */
  height       : var(--code-block-topBar-all-dot-size) !important;
  width        : var(--code-block-topBar-all-dot-size) !important;
  background   : var(--code-block-topBar-redDot-color) !important;
}
```
