### ISSUE TITLE
选中大量文字时，代码块内文字颜色为白色

### ISSUE THREAD

**Issue by LXTlogic** [jinghu-moon/typora-see-yue-theme#14]
在最新版（1.3.3）中，出现选中大量文字时，代码框内显示发白，1.3.2版本无问题
如图所示：
**1.3.3**
![屏幕截图 2022-08-21 134845](https://user-images.githubusercontent.com/75785634/185777893-97ebb7ae-39fb-4fb8-aa7b-4de5e5577f52.png)
**1.3.2**
![屏幕截图 2022-08-21 135336](https://user-images.githubusercontent.com/75785634/185777901-18f8ea2e-6405-40a8-a854-7ba07ac1e684.png)

图中是选择代码框前以及代码框之后不同版本的差异

**Comment by jinghu-moon** [comment]
好的，下个版本修复。

**Comment by jinghu-moon** [comment]
在 `code-snippet.css` 加入以下代码。

```css
/* 文本选中样式 */
::selection,
/* 代码块文本选中样式 */
pre ::selection,
.CodeMirror-selected,
.CodeMirror-selectedtext {
  color           : #fff !important;
  background-color: #7caad2 !important;
}
```
