### ISSUE TITLE
🛠 提高主题加载速度

### ISSUE THREAD

**Issue by jinghu-moon** [jinghu-moon/typora-see-yue-theme#16]
### 提高主题加载速度的方法

如果你使用这种方法，开发者认为 **HarmonyOS_Sans_SC_Regular** 挺不错的。

使用此方法，主题加载时间大致减半。

1. 删除 / 注释 `fonts.css` 文件内所有代码。

2. `fonts.css` 文件添加如下代码：

   ```css
   @font-face {
     font-family : "玄宋45S";
     src         : url("../Fonts/Chinese-Fonts/HYXuanSong45S.woff2");
     font-display: swap;
   }
   
   @font-face {
     font-family : "Lora-Regular";
     src         : url("../Fonts/English-Fonts/Lora-Regular.woff2");
     font-display: swap;
   }
   
   /* 中、英文字体，请按自己的喜好选择 */
   ```

3. `root-element.css` 文件添加以下代码：

   ```css
   :root {
       --html-text-en-font: "Lora-Regular";
       --html-text-cn-font: "玄宋45S";;
   }
   ```

4. `see-yue.css` 文件开头在 `html` 选择器添加以下代码：

   ```css
   html {
       font-family: var(--html-text-en-font), var(--html-text-cn-font);
   }
   ```
