### ISSUE TITLE
代码块的语言输入框遮挡下方的代码块

### ISSUE THREAD

**Issue by chenshanb3** [jinghu-moon/typora-see-yue-theme#23]
两个代码块之间的距离太小，上面的遮住了下面的
<img width="691" alt="image" src="https://user-images.githubusercontent.com/96278502/191882634-a2aba00d-d705-47c8-bd41-9d09c08d90b4.png">

**Comment by jinghu-moon** [comment]
下个版本修复，预计国庆前后发版。或者按以下方法修复。

`code-block.css` 文件修改如下：
```css
#write .md-fences {
  -webkit-font-smoothing: initial;
  margin                : 1.5rem 0 !important; /* 改为 2rem 0 !imporant */
  padding               : 0.3rem 0 !important;
  line-height           : 1.3rem;
  /* 背景色 */
  background-color      : var(--code-block-bg-color);
  word-wrap             : normal;
  box-shadow            : 0px 0px 10px rgba(0, 0, 0, 0.15);
    border-radius         : var(--code-block-bg-radius);
}

/* 代码块输入框 */
#write .code-tooltip {
  width      : auto;
  line-height: 1.5;
  font-size  : 16px;
  box-shadow : 0px 0px 10px rgb(0 0 0 / 30%);
  padding    : 0;
  margin     : 0;
  border     : none;
  position   : relative;
  top        : 20px; /* 改为 12px */
}
```
