### ISSUE TITLE
图片大小缩放不起作用

### ISSUE THREAD

**Issue by Xsakura1314** [jinghu-moon/typora-see-yue-theme#30]
see-yue 版本：1.3.3

在使用 **Zoom Image** 命令缩放图片时，图片的大小不会改变，而且一些小的图片会显示得很大。

![image](https://user-images.githubusercontent.com/59106419/203556188-34620266-c907-430f-a11b-a46b1f57b756.png)

**Comment by Xsakura1314** [comment]
看了一下，应该是统一设置图片大小导致的。

应该在 **images.css** 文件中去到图片的宽度属性

```css
img {
  border-radius: var(--image-radius);
  border       : none;
  transition   : .4s;
  /* 取消统一宽度 */
  /* width        : var(--image-size);  */
  box-shadow   : var(--image-shadow);
}
```

![image](https://user-images.githubusercontent.com/59106419/203558511-06ba6b9a-76dc-48d7-9ea8-81b560ca68e0.png)
