### ISSUE TITLE
脚注悬浮窗中的行内代码

### ISSUE THREAD

**Issue by cfikt** [jinghu-moon/typora-see-yue-theme#35]
你好呀，请问这里的样式，比如大小、颜色、字体等需要怎么修改牙
![image](https://user-images.githubusercontent.com/109979597/231146877-5beb1b82-406d-486c-857b-190ecd8115d6.png)

**Comment by jinghu-moon** [comment]
在外面，电脑不在身边。预计九点左右回家。这不是我的主题吧？

**Comment by cfikt** [comment]
是你的，我自己改过了

**Comment by jinghu-moon** [comment]
尴尬，v1.4 改动有点大。没认出来。


你可以参考下面的代码修改。
```css
/* 正文脚注悬浮框 */
.code-tooltip.md-hover-tip {
  background   : var(--hover-writeArea-footnote-tip-bg-color);
  font-size    : var(--hover-writeArea-footnote-tip-text-size);
  border-radius: 3px;
  padding      : 0;
  box-shadow   : none;
  min-width    : 50px;
  font-family  : "RobotoMono", "霞鹜文楷";
  opacity      : 1;
}

/* 悬浮框内容 */
.md-hover-tip .code-tooltip-content {
  border-radius: 3px;
  opacity      : .9;
  margin-top   : -2px;
  line-height  : 1.2em;
  color        : var(--hover-writeArea-footnote-tip-text-color);
  text-align   : inherit;
}

.md-hover-tip  a {
  
}

.md-hover-tip  strong {
  
}
```
