### ISSUE TITLE
代码块编辑时光标消失

### ISSUE THREAD

**Issue by luceln** [jinghu-moon/typora-see-yue-theme#40]
1. 主题是最新的，使用的是Salt版本
2. 代码块在编辑时，字母后面敲一个空格，然后光标消失了，再敲一个空格，光标跳到下一个位置出现
3. 此时继续敲空格，按两次才会空一格
4. Typora版本是1.5.12

**Comment by jinghu-moon** [comment]
```css
  --code-block-lines-horizontal-white-space: normal;
  --code-block-lines-horizontal-overflow-x : auto;
```

上面代码注释注释掉，即可。上面代码作用是代码行横向滚动，不过好像有点问题。下个版本尝试修复

**Comment by Aurora-kite** [comment]
> ```css
>   --code-block-lines-horizontal-white-space: normal;
>   --code-block-lines-horizontal-overflow-x : auto;
> ```
> 
> 上面代码注释注释掉，即可。上面代码作用是代码行横向滚动，不过好像有点问题。下个版本尝试修复

即使注释后，重启电脑后table和空格还是有问题，没有用

**Comment by jinghu-moon** [comment]
`SeeYue/code-block/code-block.css` 文件注释以下代码

```css
#write pre.md-fences .CodeMirror-wrap .CodeMirror-code pre {
    overflow-x : var(--code-block-lines-horizontal-overflow-x) !important;
    white-space: var(--code-block-lines-horizontal-white-space) !important;
}
```

应该就可以了。

预计下个版本会移除代码块横向滚动功能，来修复这个 bug。
