### ISSUE TITLE
Dark主题的YAML背景色太浅

### ISSUE THREAD

**Issue by kewtgh** [jinghu-moon/typora-see-yue-theme#41]
Dark主题的背景色太浅，文字不清晰。
![Snipaste_2023-05-28_05-46-19](https://github.com/jinghu-moon/typora-see-yue-theme/assets/55637096/feaee545-6c9c-481d-b36a-59219df0952e)

**Comment by jinghu-moon** [comment]
`SeeYue/CSS/custom` 路径下打开 `custom-dark.css` 文件，添加以下代码。

```css
pre.md-meta-block {
    background: #1f232a;
    font-family: 'Fira';
    line-height: 1.6;
    padding: 10px;
    border-radius: 5px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, .15);
    font-size: inherit;
}
```

下个版本会改善这个问题。
