### ISSUE TITLE
代码块纵向滚动显示问题

### ISSUE THREAD

**Issue by luceln** [jinghu-moon/typora-see-yue-theme#48]
1. 代码块在19行出现滚动条时，第19行代码只显示出部分。
2. 手动划到最底部后，再次编辑第19行代码，位置会跳回到刚才的位置（即显示部分文字）。
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/62422565/ba565ce3-1a4e-46ab-b63b-ef0f4325d64f)

**Comment by jinghu-moon** [comment]
代码块横向滚动有问题，目前没有找到比较好的解决方法。在考虑下个版本是否去掉该功能。🙃

**Comment by jinghu-moon** [comment]
昨晚没仔细看问题。但应该与代码块横向滚动条有关，`xxxx-configs.css` 注释下面代码，应该可以解决。

```css
  --code-block-lines-horizontal-white-space: normal;
  --code-block-lines-horizontal-overflow-x : auto;
```

**Comment by luceln** [comment]
> 昨天没仔细看问题。但应该与代码块横向滚动条有关，`xxxx-configs.css`注释下面代码，应该可以解决。
> 
> ```css
>   --code-block-lines-horizontal-white-space: normal;
>   --code-block-lines-horizontal-overflow-x : auto;
> ```

**Comment by luceln** [comment]
注释了没有效果，而且我发现鼠标单击最后一行也会出现这种情况

**Comment by jinghu-moon** [comment]
SeeYue/code-block/ 路径下 `code-block.css` 注释下面代码，应该可以吧？

```css
  /* 代码块行横向滚轮 */
  #write pre.md-fences .CodeMirror-wrap .CodeMirror-code pre {
    overflow-x : var(--code-block-lines-horizontal-overflow-x) !important;
    white-space: var(--code-block-lines-horizontal-white-space) !important;
  }
```
