### ISSUE TITLE
代码块中高亮显示问题

### ISSUE THREAD

**Issue by tianming-yun** [jinghu-moon/typora-see-yue-theme#52]
您好，SeeYue主题真的很好用，但是最近发现了一个问题，就是某些代码块中的单词会标红（高亮？）这些高亮的也不一定是关键词，而且没找到高亮的规律，有些地方显示，有些地方不显示。对css了解不多，自己找了很久也没明白，所以如何取消这样的高亮呢？
烦请作者提示一下，感谢~~~
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/102896420/0dee61e6-667c-4c52-b250-31263b172fe1)

**Comment by jinghu-moon** [comment]
SeeYue/CSS/code-block 路径，打开 ligh-theme.css 文件，注释掉以下代码，即可。

```css
/* 错误 */
.cm-s-inner .cm-error {
  color           : #fff;
  background-color: #ec5f67;
}
```

这段是错误代码提示，不过好像不太智能。
