### ISSUE TITLE
目录字体颜色不统一

### ISSUE THREAD

**Issue by Aurora-kite** [jinghu-moon/typora-see-yue-theme#56]
对于各个标题如果加粗了，那么目录内该字体颜色为黑色，而其他标题为蓝色，能不能统一为蓝色
![image](https://github.com/jinghu-moon/typora-see-yue-theme/assets/85811651/1730c511-5c09-4756-bee4-fb304ff4c538)

**Comment by jinghu-moon** [comment]
1. 打开 `inline-elemet.css` ，修改如下：

   ```css
   #write p[mdtype="paragraph"] strong {
     font-family: var(--bold-text-font);
     color      : var(--bold-text-color);
     font-size  : var(--bold-text-size);
     font-weight: normal !important;
     padding    : 0 1px;
   }
   ```

2. 打开 `contents.css` ，末尾添加如下代码。

   ```css
   #write :is(.md-toc-h1, .md-toc-h2, .md-toc-h3, .md-toc-h4, .md-toc-h5, .md-toc-h6) .md-toc-inner strong,
   :is(.md-toc-h1, .md-toc-h2, .md-toc-h3, .md-toc-h4, .md-toc-h5, .md-toc-h6):hover .md-toc-inner strong {
     font-weight: normal !important;
   }
   ```


标题字体已经是加粗字体，再加粗，只是改变了字体颜色。如果你要修改字体颜色，`xxxx-config.css` 给了配置代码。
