### ISSUE TITLE
关于编程语言显示

### ISSUE THREAD

**Issue by ADguyCN990** [jinghu-moon/typora-see-yue-theme#6]
c++语言显示出来的是C#。

**Comment by jinghu-moon** [comment]
`code-language.css` 文件，第 103 行，修改如下。

```css
pre[lang$="c#"]:after,
pre[lang$="C#"]:after,
pre[lang$="csharp"]:after,
pre[lang$="CSharp"]:after {
  content: "C#";
}
```

下个版本会修复。感谢反馈。

v1.3 预计在下周三之前发布。

v1,3 更新进度请看 See Yue 主题开发计划： https://github.com/users/jinghu-moon/projects/1/views/1
