### ISSUE TITLE
代码块缩进显示不正确，另外代码块如何去掉滚动条（想直接查看整块代码😀）。

### ISSUE THREAD

**Issue by longyuigb456** [jinghu-moon/typora-see-yue-theme#60]
<img width="1034" alt="iShot_2024-01-24_09 10 46" src="https://github.com/jinghu-moon/typora-see-yue-theme/assets/154716246/87b24229-f40f-411d-bd8f-4bb15a49338d">

**Comment by jinghu-moon** [comment]
打开 SeeYue/CSS/code-block/code-block.css，注释掉以下代码

```css
/* 代码块行横向滚轮 */
#write pre.md-fences .CodeMirror-wrap .CodeMirror-code pre {
  overflow-x : var(--code-block-lines-horizontal-overflow-x) !important;
  white-space: var(--code-block-lines-horizontal-white-space) !important;
}

/* 代码块内容过多，滚动显示 */
  pre div.CodeMirror-scroll {
  position       : relative;
  max-height     : var(--code-block-max-height) !important;
  overflow-y     : auto;
  cursor         : auto !important;
  overflow-x     : hidden !important;
  scroll-behavior: smooth;
}
```

重启，即可
