### ISSUE TITLE
代码框中制表符无法显示

### ISSUE THREAD

**Issue by NOBAINOLIFE** [jinghu-moon/typora-see-yue-theme#76]
您好，这是问题描述：
代码快中的制表符不能正常显示，但是制表符还是成功输入了。
比如说下面是代码块中的代码：

```java
int i = 2;//定义一个整形变量

在;和//之间其实是有3个制表符的，但是;和//还是连在一起的，若要删除;还要先删除;后面看不见的3个制表符才行

使用的是see yue1.4，typora1.9.5-windows-x64

尝试了其他issue中的方法都没有解决，T^T

**Comment by NOBAINOLIFE** [comment]
打空格的时候也是，输入了一个空格后输入光标就不见了

**Comment by jinghu-moon** [comment]
`SeeYue\CSS\code-block\code-block.css` 删除以下代码：

```css
  /* 代码块行横向滚轮 */
  #write pre.md-fences .CodeMirror-wrap .CodeMirror-code pre {
    overflow-x : var(--code-block-lines-horizontal-overflow-x) !important;
    white-space: var(--code-block-lines-horizontal-white-space) !important;
  }

  /* 代码块内容过多，滚动显示 */
  pre div.CodeMirror-scroll {
    position  : relative;
    max-height: var(--code-block-max-height) !important;
    overflow-y: auto;
    cursor    : auto !important;
    overflow-x: hidden !important;
  }
```

我删除这段代码，可以解决问题。你试试。
